name: tests
on: pull_request
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Setup DynamoDB Local
              uses: rrainn/dynamodb-action@v2.0.0
              with:
                  sharedDb: true
                  port: 8000
                  cors: '*'
            - uses: actions/checkout@v2
            - run: sam --version
            - run: aws configure set aws_access_key_id fakeMyKeyId
            - run: aws configure set aws_secret_access_key fakeSecretAccessKey
            - run: npm i
            - run: npm run build:workflow
            - run: npm run start:workflow &
            - run: sleep 20
            - run: npm test
